### ISSUE TITLE
Code for 30EUR off: REF6GQGS87DGY is invalid

### ISSUE THREAD

**Issue by mawa85** [peteh/nuki-esp32-bridge#3]
Just to let you know Nuki Shop says the code is invalid

Thanks for this project

**Comment by peteh** [comment]
Hi, 

thanks, looks like they are only valid for 30days. 

Here is a 10% off: REFMMG3CQPAS5 

There is also another project called Nuki Hub that is more feature complete if you use peripherals especially.
